name: Deploy

on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: bundle exec rubocop

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in Amazon EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY}}
          HOSTNAME: ${{secrets.HOSTNAME}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          cd /home/ec2-user/cd-test &&
          git fetch --all &&
          git reset --hard origin/main &&
          bundle install &&
          lsof -t -i:4567 | xargs --no-run-if-empty kill -9 &&
          screen -dm bundle exec ruby app.rb -o 0.0.0.0
          '

